gui:
  scrollHeight: 10
  expandFocusedSidePanel: true
  theme:
    selectedLineBgColor:
    - reverse
    - bold
confirmOnQuit: true
quitOnTopLevelReturn: true
promptToReturnFromSubprocess: false
skipRewordInEditorWarning: false
notARepository: skip
git:
  autoFetch: true
  autoRefresh: false

keybinding:
  universal:
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
    scrollUpMain-alt2: <c-u>
    scrollDownMain-alt2: <c-d>
